name: CI

on: [push]

jobs:
  build-test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: "8.3"

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: "coverage"
        with:
          php_version: "8.3"
          php_extensions: "xdebug"
          bootstrap: "vendor/autoload.php"
          configuration: "build/config/phpunit.xml"
          test_suffix: "Test.php"
          coverage_clover: "coverage.xml"
#          args: --display-warnings --display-errors

      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
